MVC_Library/Models/Book.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace MVC_LIbrary.Models
{
    public class Book
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Year { get; set; }

        internal List<Book> Books = new List<Book>();
    }
}

MVC_Library/Controllers/AuthorController.cs
using System.Web.Mvc;
using System.Collections.Generic;
using MVC_Library.Repositories;
using MVC_Library.Models;

namespace MVC_Library.Controllers
{
    public class AuthorController : Controller
    {
        /// <summary>
        /// GET: /Initial/
        /// 
        /// List/Get all users into the database
        /// </summary>
        /// <returns>
        /// All users into the database
        /// </returns>
        public ActionResult Index()
        {
            IEnumerable<AuthorModels> authors;
            using (var repo = new AuthorRepository())
            {
                authors = repo.GetAll();
            }
            foreach (var author in authors)
            {
                using (var repo_a = new BookRepository())
                {
                    author.BookList = (List<BookModels>)(repo_a.FindBooksByAuthor(author.Id));
                }
            }

            return View("Index", authors);
        }

        /// <summary>
        /// GET: /Initial/Details/5
        /// 
        /// Get the entire data of a given user id
        /// </summary>
        /// <param name="id">The id for searching into database</param>
        /// <returns>The found data of the given id</returns>
        public ActionResult Details(int id)
        {
            return View("Details", GetAuthor(id));
        }

        /// <summary>
        /// GET: /Initial/Create
        /// 
        /// Show the form to create a new user
        /// </summary>
        /// <returns>
        /// Form to create a new user
        /// </returns>
        public ActionResult Create()
        {
            return View();
        }

        /// <summary>
        /// POST: /Initial/Create
        /// 
        /// Create a new user with the given data
        /// </summary>
        /// <param name="author">The user data to put it into database</param>
        /// <returns>
        /// Redirect to navigation page
        /// </returns>
        [HttpPost]
        public ActionResult Create(AuthorModels author)
        {
            try
            {
                using (var repo = new AuthorRepository())
                {
                    repo.Create(author);
                }

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        /// <summary>
        /// GET: /Initial/Edit/5
        /// 
        /// Show the user data to be edited on form
        /// </summary>
        /// <param name="id">Id to search on database</param>
        /// <returns>
        /// The edit view loaded with user data
        /// </returns>
        public ActionResult Edit(int id)
        {
            return View("Edit", GetAuthor(id));
        }

        /// <summary>
        /// POST: /Initial/Edit/5
        /// 
        /// Persists the modifications into user data inside the database
        /// </summary>
        /// <param name="id">Edited user data</param>
        /// <param name="editAuthor">Id of the edited user</param>
        /// <returns>
        /// Redirect to navigation page
        /// </returns>
        [HttpPost]
        public ActionResult Edit(int id, AuthorModels editAuthor)
        {
            try
            {
                using (var repo = new AuthorRepository())
                {
                    repo.Edit(editAuthor);
                }

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Initial/Delete/5

        public ActionResult Delete(int id)
        {
            return View("Delete", GetAuthor(id));
        }

        //
        // POST: /Initial/Delete/5

        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                using (var repo = new AuthorRepository())
                {
                    repo.Delete(id);
                }
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        /// <summary>
        /// Get the user inside the database using the id with param to search
        /// </summary>
        /// <param name="id">AuthorModels id to search</param>
        /// <returns>
        /// The found user data
        /// </returns>
        private AuthorModels GetAuthor(int id)
        {
            AuthorModels model;
            using (var repo = new AuthorRepository())
            {
                model = repo.Details(id);
            }

            return model;
        }
    }
}

MVC_Library/Controllers/BookController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVC_Library.Models;
using MVC_Library.Repositories;
using MVC_Library.Repositories.DAL;

namespace MVC_Library.Controllers
{
    public class BookController : Controller
    {

        //[HttpGet]
        public ActionResult TakeBook(int bookId, string username)
        {
            if (!String.IsNullOrEmpty(username))
            {
                var book = GetBook(bookId);
                if ((int)book.Quantity > 0)
                {
                    book.Quantity--;
                    using (var repo = new BookRepository())
                    {
                        repo.Edit(book);
                        repo.BindBookToUser(book.Id, username);
                    }
                }
            }
            return RedirectToAction("Index");
        }

        //
        // GET: /BookModels/
        public ActionResult Index()
        {
            IEnumerable<BookModels> books;
            using (var repo = new BookRepository())
            {
                books = repo.FindBooks();
            }
            foreach (var book in books)
            {
                using (var repo_a = new AuthorRepository())
                {
                    //ViewBag.AuthorList = repo.GetAll().ToList();
                    book.AuthorList = repo_a.FindAuthorsByBook(book.Id).ToList();
                }
            }

            return View("Index", books);
        }

        //
        // GET: /BookModels/Details/5

        public ActionResult Details(int id)
        {
            var book = GetBook(id);

            using (var repo_a = new AuthorRepository())
            {
                ViewBag.AuthorList = repo_a.GetAll();
                //ViewBag.AuthorList = repo_a.FindAuthorsByBook(book.Id).ToList();
            }

            return View("Details", GetBook(id));
        }

        private BookModels GetBook(int bookId)
        {
            var model = new BookModels();
            using (var repo = new BookRepository())
            {
                model = repo.Details(bookId);
            }
            using (var repo_a = new AuthorRepository())
            {
                model.AuthorList = repo_a.FindAuthorsByBook(bookId).ToList();
            }
            foreach (var i in model.AuthorList)
            {
                model.SelectedAuthors.Add(i.Id);
            }
            return model;
        }

        /// <summary>
        /// GET: /Initial/Create
        /// 
        /// Show the form to create a new user
        /// </summary>
        /// <returns>
        /// Form to create a new user
        /// </returns>
        /// 
        public ActionResult Create()
        {
            var model = new BookModels();
            using (var repo = new AuthorRepository())
            {
                model.AuthorList = repo.GetAll().ToList();
            }
            return View(model);
        }

        /// <summary>
        /// POST: /Initial/Create
        /// 
        /// Create a new user with the given data
        /// </summary>
        /// <param name="user">The user data to put it into database</param>
        /// <returns>
        /// Redirect to navigation page
        /// </returns>
        [HttpPost]
        public ActionResult Create(BookModels book)
        {
            try
            {
                using (var repo = new BookRepository())
                {
                    repo.Create(book);
                    book.Id = repo.GetBookByTitle(book.Title);
                }

                foreach (var author in book.SelectedAuthors)
                {
                    using (var repo = new BookRepository())
                    {
                        repo.BindAuthorToBook(book.Id, author);
                    }
                }

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /BookModels/Edit/5
        public ActionResult Edit(int id)
        {
            using (var repo = new AuthorRepository())
            {
                ViewBag.AuthorList = repo.GetAll().ToList();
            }
            return View("Edit", GetBook(id));
        }

        //
        // POST: /BookModels/Edit/5

        [HttpPost]
        public ActionResult Edit(int id, BookModels editBook)
        {
            try
            {
                using (var repo = new BookRepository())
                {
                    repo.Edit(editBook);
                }

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /BookModels/Delete/5

        public ActionResult Delete(int id)
        {
            return View("Delete", GetBook(id));
        }

        //
        // POST: /BookModels/Delete/5

        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                using (var repo = new BookRepository())
                {
                    repo.Delete(id);
                }

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

MVC_Library/Views/Book/Create.cshtml
@model MVC_Library.Models.BookModels

@{
    ViewBag.Title = "Adding book:";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="col-md-8 col-md-offset-2">
    <h2>@ViewBag.Title</h2>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)

        <fieldset>
            <div class="editor-label">
                <strong>@Html.LabelFor(model => model.Title)</strong>
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Title)
                @Html.ValidationMessageFor(model => model.Title)
            </div>

            <div class="editor-label">
                <strong>@Html.LabelFor(model => model.Year)</strong>
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Year)
                @Html.ValidationMessageFor(model => model.Year)
            </div>

            <div class="editor-label">
                <strong>@Html.LabelFor(model => model.Quantity)</strong>
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Quantity)
                @Html.ValidationMessageFor(model => model.Quantity)
            </div>

            <div class="editor-label">
                <strong>@Html.LabelFor(model => model.AuthorList)</strong>
            </div>
            <div class="editor-field">
                @Html.ListBoxFor(model => model.SelectedAuthors, new MultiSelectList(Model.AuthorList, "Id", "Name"), new { id = "authors" })
            </div>

            <p>
                <br />
                <input type="submit" value="Accept" />
            </p>
        </fieldset>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }
</div>

MVC_Library/Views/Book/Delete.cshtml
@model MVC_Library.Models.BookModels
@{
    ViewBag.Title = "Delete";
}
<div class="col-md-8 col-md-offset-2">
    <h2>Delete</h2>
    <h3>Are you sure you want to delete this?</h3>
    <fieldset>
        <div class="editor-label">
            <strong>@Html.LabelFor(model => model.Title)</strong>
        </div>
        <div class="display-field">
            @Html.DisplayFor(model => model.Title)
        </div>
        <div class="editor-label">
            <strong>@Html.LabelFor(model => model.Year)</strong>
        </div>
        <div class="display-field">
            @Html.DisplayFor(model => model.Year)
        </div>
        <div class="editor-label">
            <strong>@Html.LabelFor(model => model.Quantity)</strong>
        </div>
        <div class="display-field">
            @Html.DisplayFor(model => model.Quantity)
        </div>

        <div class="editor-label">
            <strong>@Html.DisplayNameFor(model => model.AuthorList)</strong>
        </div>
        <div>
            @foreach (var al in Model.AuthorList)
            {
                @Html.ActionLink(al.Name, "Details", "Author", routeValues: new { id = al.Id }, htmlAttributes: new { @class = "author", title = "view" }) <br />
            }
        </div>
        <br />
    </fieldset>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <p>
            <input type="submit" value="Delete" /> |
            @Html.ActionLink("Back to List", "Index")
        </p>
    }
</div>

MVC_Library/Views/Book/Details.cshtml
@model MVC_Library.Models.BookModels

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="col-md-8 col-md-offset-2">
    <h2>Details</h2>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)

        <fieldset>
            <div class="display-label">
                <strong>@Html.DisplayNameFor(model => model.Title)</strong>
            </div>
            <div class="display-field">
                @Html.DisplayFor(model => model.Title)
            </div>

            <div class="display-label">
                <strong>@Html.DisplayNameFor(model => model.Year)</strong>
            </div>
            <div class="display-field">
                @Html.DisplayFor(model => model.Year)
            </div>
            
            <div class="display-label">
                <strong>@Html.DisplayNameFor(model => model.Quantity)</strong>
            </div>
            <div class="display-field">
                @Html.DisplayFor(model => model.Quantity)
            </div>

            <div class="editor-label">
                <strong>@Html.LabelFor(model => model.AuthorList)</strong>
            </div>
            <div class="editor-field">
                @foreach (var al in Model.AuthorList)
                {
                    @Html.ActionLink(al.Name, "Details", "Author", routeValues: new { id = al.Id }, htmlAttributes: new { @class = "author", title = "view" }) <br />
                }
            </div>

           <br />

        </fieldset>
    }
    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
        @Html.ActionLink("Back to List", "Index")
    </p>
</div>

MVC_Library/Views/Book/Edit.cshtml
@model MVC_Library.Models.BookModels

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="col-md-8 col-md-offset-2">
    <h2>Book edit</h2>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)

        <fieldset>
            <div class="editor-label">
                <strong>@Html.LabelFor(model => model.Title)</strong>
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Title)
                @Html.ValidationMessageFor(model => model.Title)
            </div>
            <div class="editor-label">
                <strong>@Html.LabelFor(model => model.Year)</strong>
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Year )
                @Html.ValidationMessageFor(model => model.Year)
            </div>
            <div class="editor-label">
                <strong>@Html.LabelFor(model => model.Quantity)</strong>
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Quantity)
                @Html.ValidationMessageFor(model => model.Quantity)
            </div>

            <div class="editor-label">
                <strong>@Html.LabelFor(model => model.AuthorList)</strong>
            </div>
            <div class="editor-field">
                @*@Html.ListBoxFor(model => model.SelectedFields, new MultiSelectList(ViewBag.AuthorList, "Id", "Name"), new { id = "authors" })*@
                @*@Html.ListBoxFor(model => model.SelectedFields, new MultiSelectList(Model.AuthorList, "Id", "Name"), new { id = "authors" })*@
                @Html.ListBoxFor(model => model.SelectedAuthors, new MultiSelectList(ViewBag.AuthorList, "Id", "Name", Model.SelectedAuthors), new { id = "authors" })
            </div>
            @*<div class="editor-field">
            @Html.ListBoxFor(model => model.SelectedFields, new MultiSelectList(ViewBag.AuthorList, Model.SelectedFields), new { id = "authors" })

            @Html.ListBox(model => model.SelectedFields, new MultiSelectList(Model.AuthorList, "Id", "Name"), new { id = "authors" })
            @Html.ListBoxFor(m => m.SelectedFields, Model.AuthorList.Select(f => new SelectListItem { Text = f.Name, Value = f.Id }), new { Multiple = "multiple" })

        </div>*@

            <p>
                <input type="submit" value="Save" />
            </p>
        </fieldset>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }
</div>

MVC_Library/Views/Book/Index.cshtml
@model IEnumerable<MVC_Library.Models.BookModels>

@{
    ViewBag.Title = "Books";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="col-md-8 col-md-offset-2">
    <h2>Books</h2>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)
        @Html.ActionLink("Add book", "Create", "Book", routeValues: null, htmlAttributes: null)

        <style type="text/css">
            .gTable {
                border-collapse: collapse;
                border: 1px solid #c0c0c0;
                width: 100%;
            }

                .gTable tr td {
                    padding: 5px;
                    border: 1px solid #c0c0c0;
                }

                .gTable tr:nth-child(2n+1) {
                    background-color: #eaeaea;
                }

                .gTable tr th {
                    background-color: #8fd9ff;
                }

            tfoot tr td {
                background-color: #ffd800 !important;
            }

            .gTable tr:hover {
                background-color: #fffddc;
            }

            .selectedRow {
                background-color: #ff6a00 !important;
            }
        </style>
        <div id="tblGrid">
            @{
        var g_style = new WebGrid(source: Model,
              rowsPerPage: 10);
            @g_style.GetHtml(
tableStyle: "gTable",
headerStyle: "gHead",
footerStyle: "gFooter",
rowStyle: "gridRow",
alternatingRowStyle: "gridAltRow",
        columns: g_style.Columns(
                g_style.Column("Id", "Id"),
                g_style.Column("Title", "Title"),
                        g_style.Column("Quantity", "Quantity")))
            }
        </div>

        @*<table class="table">
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.Title)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Year)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.AuthorList)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Quantity)
                            </th>
                            <th>
                                Operations
                            </th>
                        </tr>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Title)
                                    <p>
                                        @if (item.Quantity > 0)
                                        {
                                            <button onclick="location.href='@Url.Action("TakeBook", "Book", new { bookId = item.Id, username = User.Identity.Name })';return false;">Take</button>
                                        }
                                    </p>
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Year)
                                </td>
                                <td>
                                    @foreach (var al in item.AuthorList)
                                    {
                                        @Html.ActionLink(al.Name, "Details", "Author", routeValues: new { id = al.Id }, htmlAttributes: new { @class = "author", title = "view" }) <br />
                                    }
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Quantity)
                                </td>
                                <td>
                                    @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                                    @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                                    @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                                </td>
                            </tr>
                        }
                    </table>
            </div>*@
    }
</div>